name: weather_app
description: "See the real weather in Weather Cloud"
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.11.4

dependencies:
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  dart_suncalc: ^0.2.1
  flutter_dotenv: ^5.2.1
  shake: ^3.0.0
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  package_info_plus: ^10.2.1
  open_filex: ^4.7.0
  cloud_firestore: ^6.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  
  # ===== ДОБАВЬ ЭТО =====
  assets:
    - .env
  # ======================

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appicon.png"
  adaptive_icon_background: "#191919"
  min_sdk_android: 21